name: Dart CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install deps
        run: dart pub get

      - name: Analyze
        run: dart analyze

      # ---- Tests + LCOV coverage ----
      - name: Test with coverage
        run: |
          dart test --coverage=coverage
          dart run coverage:format_coverage \
            --lcov \
            --in=coverage \
            --out=coverage/lcov.info \
            --packages=.dart_tool/package_config.json \
            --report-on=lib

      # ---- Hard coverage gate (adjust threshold as you like) ----
      - name: Enforce coverage ≥ 80%
        run: |
          python - <<'PY'
          import sys
          hit=total=0
          with open('coverage/lcov.info') as f:
              for ln in f:
                  if ln.startswith('LH:'): hit  += int(ln[3:].strip())
                  if ln.startswith('LF:'): total += int(ln[3:].strip())
          pct = (100.0*hit/total) if total else 0.0
          print(f"Coverage: {pct:.2f}% (LH={hit}, LF={total})")
          sys.exit(0 if pct >= 70.0 else 1) 
          PY

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: lcov
          path: coverage/lcov.info

      # ---- Codecov upload (optional & non-blocking if token missing) ----
      - name: Upload to Codecov
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
