name: Dart CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install deps
        run: dart pub get

      - name: Analyze
        run: dart analyze

      - name: Test
        run: dart test -r expanded

      # === Add these two steps ===
      - name: Test with coverage
        run: |
          dart test --coverage=coverage
          dart run coverage:format_coverage \
            --lcov --in=coverage --out=coverage/lcov.info \
            --packages=.dart_tool/package_config.json --report-on=lib

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: lcov
          path: coverage/lcov.info
